In [73]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [74]:
data = pd.read_csv('drug200.csv')

In [75]:
data.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [76]:
#BP: Blood Pressure Levels
#Na_to_K : Na to Potassium Ration

In [77]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          200 non-null    int64
 1   Sex          200 non-null    object
 2   BP           200 non-null    object
 3   Cholesterol  200 non-null    object
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB

In [78]:
data.describe()

              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [79]:
# Korelasyona sokmak için Sex,BP,Chloesterol sütunlarını encode etmemiz gerekiyor.

In [80]:
#Sex : Cinsiyet Kolonu Label Encode

In [81]:
from sklearn.preprocessing import LabelEncoder

In [82]:
encoder = LabelEncoder()

In [83]:
data["Sex"] = encoder.fit_transform(data["Sex"])

In [84]:
data["Sex"].unique()

array([0, 1])

In [85]:
#BP : Kan Basıncı Kolonu Ordinal Encode

In [86]:
from sklearn.preprocessing import OrdinalEncoder

In [87]:
data["BP"].unique()

array(['HIGH', 'LOW', 'NORMAL'], dtype=object)

In [88]:
siralama = [['LOW','NORMAL','HIGH']]

In [89]:
encoder2 = OrdinalEncoder(categories=siralama)

In [90]:
data['BP'] = encoder2.fit_transform(data[['BP']])

In [91]:
data["BP"].unique()

array([2., 0., 1.])

In [92]:
#Cholesterol : Kolesterol Kolonu Ordinal Encode

In [93]:
data["Cholesterol"].unique()

array(['HIGH', 'NORMAL'], dtype=object)

In [94]:
siralama2 = [['NORMAL','HIGH']]

In [95]:
encoder3 = OrdinalEncoder(categories=siralama2)

In [96]:
data['Cholesterol'] = encoder3.fit_transform(data[['Cholesterol']])

In [97]:
data.describe()

              Age         Sex          BP  Cholesterol     Na_to_K
count  200.000000  200.000000  200.000000   200.000000  200.000000
mean    44.315000    0.520000    1.065000     0.515000   16.084485
std     16.544315    0.500854    0.839224     0.501029    7.223956
min     15.000000    0.000000    0.000000     0.000000    6.269000
25%     31.000000    0.000000    0.000000     0.000000   10.445500
50%     45.000000    1.000000    1.000000     1.000000   13.936500
75%     58.000000    1.000000    2.000000     1.000000   19.380000
max     74.000000    1.000000    2.000000     1.000000   38.247000

In [98]:
data["Drug"].unique()

array(['DrugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [99]:
# Y degeri için Label Encode

In [100]:
encoder4 = LabelEncoder()

In [101]:
data["Drug"] = encoder4.fit_transform(data["Drug"])

In [102]:
data["Drug"].unique()

array([0, 3, 4, 1, 2])

In [103]:
# Verilerin uyumu ve doğru gradient işlemi için scale işlemi

In [104]:
from sklearn.preprocessing import StandardScaler

In [105]:
scaler = StandardScaler()

In [106]:
from sklearn.model_selection import train_test_split

In [107]:
X = data.drop("Drug",axis=1)
y = data["Drug"]

In [108]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=15)

In [109]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [110]:
# Logistic Regression Import

In [111]:
from sklearn.linear_model import LogisticRegression

In [112]:
reg = LogisticRegression()

In [113]:
reg.fit(X_train_scaled,y_train)
y_pred = reg.predict(X_test_scaled)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [114]:
print("Result:",accuracy_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

Result: 0.94
[[22  0  0  0  2]
 [ 0  5  1  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0 13]]
              precision    recall  f1-score   support

           0       1.00      0.92      0.96        24
           1       1.00      0.83      0.91         6
           2       0.75      1.00      0.86         3
           3       1.00      1.00      1.00         4
           4       0.87      1.00      0.93        13

    accuracy                           0.94        50
   macro avg       0.92      0.95      0.93        50
weighted avg       0.95      0.94      0.94        50

In [115]:
# LogisticRegression : 0.94

In [116]:
# SVM İle Aynı Datayı Test Etme İşlemi

In [117]:
from sklearn.svm import SVC

In [118]:
svc = SVC() #kernel: rbf olarak default

In [119]:
svc.fit(X_train_scaled,y_train)
y_pred = svc.predict(X_test_scaled)
print("Result:",accuracy_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

Result: 0.96
[[21  0  0  0  0]
 [ 1  5  1  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0 15]]
              precision    recall  f1-score   support

           0       0.95      1.00      0.98        21
           1       1.00      0.71      0.83         7
           2       0.75      1.00      0.86         3
           3       1.00      1.00      1.00         4
           4       1.00      1.00      1.00        15

    accuracy                           0.96        50
   macro avg       0.94      0.94      0.93        50
weighted avg       0.97      0.96      0.96        50

In [120]:
# SVC ile biraz daha uygun sonuç elde ettim. Biraz da grid işlemleri ile arttırmaya çalıştım.

In [121]:
from sklearn.model_selection import GridSearchCV

In [122]:
params = {
    'C' : [0.1,1,10,100,1000],
    "gamma" : ['scale','auto'],
    'kernel' : ['linear', 'poly', 'rbf', 'sigmoid']
}

In [123]:
grid = GridSearchCV(SVC(),param_grid=params,cv=5,n_jobs=-1)

In [124]:
grid.fit(X_train_scaled,y_train)

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [125]:
grid.best_params_

{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}

In [126]:
y_pred = grid.predict(X_test_scaled)
print("Result:",accuracy_score(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

Result: 0.98
[[22  0  0  0  0]
 [ 0  5  1  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       1.00      0.83      0.91         6
           2       0.75      1.00      0.86         3
           3       1.00      1.00      1.00         4
           4       1.00      1.00      1.00        15

    accuracy                           0.98        50
   macro avg       0.95      0.97      0.95        50
weighted avg       0.98      0.98      0.98        50

In [127]:
# Logistic Regresyon ile 0.94, SVC ile 0.96, hiperparametre(grid) ile birlikte 0.98 sonuç elde ettim.

## Özet

Machine Learning uygulamalarında bazen bir model işimizi çözemeyebilir. Bugün 3 işlemde de yüksek sonuç aldım fakat her zaman bu durum olacak diye bir şey yok. Önemli olan bildiklerimizi işe yarar şekilde kullanabilmek.